# Generated by Django 2.2 on 2019-07-11 21:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('comp_name', models.CharField(max_length=50)),
                ('house_nr', models.CharField(max_length=30)),
                ('post_nr', models.CharField(max_length=4)),
                ('city', models.CharField(max_length=30)),
                ('bill_city', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('tax_nr', models.CharField(max_length=20)),
                ('id_nr', models.CharField(max_length=20)),
                ('transact_acc', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('bill_number', models.CharField(max_length=20)),
                ('buyer_full_name', models.CharField(max_length=50)),
                ('buyer_house_nr', models.CharField(max_length=30)),
                ('buyer_post_nr', models.CharField(max_length=4)),
                ('id_for_vat', models.CharField(max_length=20)),
                ('task_date', models.DateField()),
                ('payment_date', models.DateField()),
                ('task', models.CharField(max_length=50)),
                ('opravilo', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('measure_unit', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
                ('cents_per_quantity', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('quantity', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=4, max_digits=10), size=None)),
                ('full_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SavedTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('comp_name', models.CharField(max_length=50)),
                ('house_nr', models.CharField(max_length=30)),
                ('post_nr', models.CharField(max_length=4)),
                ('city', models.CharField(max_length=30)),
                ('bill_city', models.CharField(max_length=30)),
                ('tax_nr', models.CharField(max_length=20)),
                ('id_nr', models.CharField(max_length=20)),
                ('transact_acc', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=50)),
            ],
        ),
    ]
